
CREATE TABLE IF NOT EXISTS TRANSACTIONS(
	WEEK INT,
    DAY INT,
	CUSTOMER_ID  VARCHAR(255),
    ARTICLE_ID INT,
    PURCHASE_AMOUNTS VARCHAR(255),
    WORKER_ID VARCHAR(255),
    TRANSACTION_TYPE VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS SCHEDULES(
	WEEK INT,
    DAY VARCHAR(255),
    WORKER_ID VARCHAR(255),
    DEPARTMENT VARCHAR(255),
    SHIFT INT
	);

CREATE TABLE IF NOT EXISTS PRICES(
	WEEK INT,
	ARTICLE_ID VARCHAR(255),
    ARTICLE_PRICE FLOAT
	);
    
CREATE TABLE IF NOT EXISTS PURCHASES(
	WEEK INT,
	ARTICLE_ID VARCHAR(255),
    AMOUNT INT
	);

CREATE TABLE IF NOT EXISTS ARTICLES(
	ARTICLE_ID VARCHAR(255),
    ARTICLE_NAME VARCHAR(255)
	);

CREATE TABLE IF NOT EXISTS WORKERS(
	WORKER_ID VARCHAR(255),
    WORKER_NAME VARCHAR(255),
    WORKER_AGE VARCHAR(255),
    WORKER_SALARY VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SUPPLIER_PRICES(
	ARTICLE_ID INT,
    SUPPLIER_PRICE FLOAT
);

DROP TABLE transactions;