# Parse the provided data, build a pairwise co-occurrence matrix, and plot a heatmap.
# We'll also save the matrix as a CSV and the heatmap as a PNG for download.

import re
import itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

raw = """
Unique combinations of merch_types and their counts:
monster: 211
laderhosen,monster: 6
monster,rice_porridge: 29
hot_dogs,monster: 36
hot_dogs,monster,rice_porridge: 60
hot_dogs,rice_porridge: 86
monster,nails: 35
rice_porridge: 120
hot_dogs: 67
ice_cream,monster: 21
hot_dogs,nails,rice_porridge: 20
hot_dogs,monster,sunscreen: 6
nails: 89
hammer,nails: 32
hammer,hot_dogs,monster,nails: 5
hammer,hot_dogs,monster,nails,rice_porridge: 11
hot_dogs,nails: 19
hammer,hot_dogs,nails: 10
hammer,hot_dogs,nails,rice_porridge: 7
hammer,monster,nails,rice_porridge: 2
hot_dogs,monster,nails: 16
hot_dogs,monster,nails,rice_porridge: 14
hammer,nails,rice_porridge: 1
hammer,hot_dogs,ice_cream,nails,rice_porridge: 5
batteries,ice_cream,nails,sunscreen: 10
batteries,hammer,ice_cream,nails: 5
ice_cream: 77
batteries,hot_dogs,rice_porridge: 18
batteries,nails: 22
ice_cream,nails,sunscreen: 16
batteries,ice_cream: 17
batteries,hot_dogs,monster,rice_porridge: 15
hammer,ice_cream,nails,sunscreen: 11
batteries,ice_cream,nails,rice_porridge: 7
hammer,hot_dogs,ice_cream,nails,rice_porridge,sunscreen: 4
ice_cream,nails: 22
hot_dogs,ice_cream,nails,rice_porridge: 10
batteries,hot_dogs,nails: 6
batteries,hot_dogs,nails,rice_porridge: 4
ice_cream,sunscreen: 76
hammer,hot_dogs,laderhosen,nails,rice_porridge: 2
hot_dogs,laderhosen,rice_porridge: 1
ice_cream,monster,nails: 15
hot_dogs,ice_cream,nails,sunscreen: 4
hammer,ice_cream,nails: 9
hot_dogs,ice_cream,monster,nails,rice_porridge,sunscreen: 7
hot_dogs,ice_cream,rice_porridge: 14
hot_dogs,ice_cream,sunscreen: 9
ice_cream,monster,nails,rice_porridge,sunscreen: 1
hot_dogs,ice_cream: 15
hot_dogs,sunscreen: 2
sunscreen: 143
laderhosen,monster,nails,rice_porridge: 2
hot_dogs,laderhosen,monster,nails: 2
hot_dogs,laderhosen,monster,nails,rice_porridge: 1
hot_dogs,monster,nails,sunscreen: 2
ice_cream,laderhosen: 5
hot_dogs,ice_cream,monster,rice_porridge,sunscreen: 24
ice_cream,monster,sunscreen: 37
monster,nails,rice_porridge: 7
monster,sunscreen: 12
monster,nails,sunscreen: 2
hammer,hot_dogs,ice_cream,nails: 2
hot_dogs,ice_cream,rice_porridge,sunscreen: 20
hot_dogs,ice_cream,nails,rice_porridge,sunscreen: 4
ice_cream,monster,nails,sunscreen: 14
gjokur_ja,hot_dogs,ice_cream,laderhosen,monster,sunscreen: 1
hammer,hot_dogs,monster,nails,rice_porridge,sunscreen: 2
hot_dogs,ice_cream,monster,sunscreen: 5
hammer,hot_dogs,ice_cream,laderhosen,nails,rice_porridge,sunscreen: 1
laderhosen: 1519
ice_cream,nails,rice_porridge,sunscreen: 4
ice_cream,monster,rice_porridge,sunscreen: 7
hot_dogs,nails,sunscreen: 4
batteries,hammer,nails: 7
batteries,nails,sunscreen: 3
batteries,hot_dogs,ice_cream,nails,rice_porridge: 1
batteries,hot_dogs,monster: 16
batteries,ice_cream,sunscreen: 35
batteries,hot_dogs,ice_cream,rice_porridge,sunscreen: 4
hammer,monster,nails: 15
batteries,nails,rice_porridge,sunscreen: 1
batteries,hot_dogs,monster,nails: 4
batteries,monster: 26
laderhosen,monster,nails: 2
ice_cream,rice_porridge,sunscreen: 18
hammer,hot_dogs,ice_cream,monster,nails,rice_porridge,sunscreen: 4
batteries,hot_dogs: 6
batteries,sunscreen: 42
batteries,ice_cream,monster,nails,sunscreen: 5
hammer,ice_cream,monster,nails,sunscreen: 9
hot_dogs,ice_cream,nails: 4
batteries,ice_cream,monster,sunscreen: 21
rice_porridge,sunscreen: 31
nails,rice_porridge: 10
batteries,hot_dogs,ice_cream,sunscreen: 2
batteries,laderhosen,nails: 2
hot_dogs,monster,rice_porridge,sunscreen: 5
batteries,hot_dogs,ice_cream,knives,monster,rice_porridge,sunscreen: 4
batteries,hot_dogs,ice_cream,monster: 3
ice_cream,laderhosen,sunscreen: 3
batteries,hot_dogs,ice_cream,monster,rice_porridge: 7
batteries,monster,nails,rice_porridge: 1
batteries,ice_cream,monster: 12
batteries,monster,rice_porridge: 4
hammer,hot_dogs,monster,nails,sunscreen: 1
hot_dogs,knives,laderhosen,monster,nails,rice_porridge: 1
batteries,hot_dogs,rice_porridge,sunscreen: 1
batteries,laderhosen: 17
batteries,hot_dogs,sunscreen: 1
gjokur_ja,laderhosen,rice_porridge,sunscreen: 1
batteries,hot_dogs,ice_cream,monster,rice_porridge,sunscreen: 5
laderhosen,sunscreen: 23
hammer,ice_cream,monster,nails: 6
batteries,hammer,hot_dogs,ice_cream,monster,nails: 3
batteries,ice_cream,laderhosen,monster,sunscreen: 2
batteries: 160
batteries,knives,monster: 15
batteries,monster,sunscreen: 3
batteries,monster,nails,sunscreen: 2
hammer,monster,nails,rice_porridge,sunscreen: 1
nails,sunscreen: 2
batteries,hot_dogs,ice_cream,rice_porridge: 7
batteries,hot_dogs,ice_cream: 4
batteries,ice_cream,rice_porridge: 8
batteries,hammer,hot_dogs,ice_cream,nails: 1
hot_dogs,ice_cream,knives,laderhosen,monster,nails,sunscreen: 1
hot_dogs,ice_cream,knives,mattress,monster,nails,rice_porridge: 1
batteries,hammer,nails,sunscreen: 3
hot_dogs,laderhosen,monster: 1
hot_dogs,laderhosen,rice_porridge,sunscreen: 1
monster,rice_porridge,sunscreen: 1
batteries,hot_dogs,monster,nails,rice_porridge,sunscreen: 3
batteries,hot_dogs,monster,rice_porridge,sunscreen: 1
batteries,gjokur_ja,hammer,laderhosen,nails: 1
batteries,hot_dogs,nails,sunscreen: 1
batteries,hot_dogs,ice_cream,nails,rice_porridge,sunscreen: 2
batteries,hot_dogs,laderhosen,monster,rice_porridge,sunscreen: 1
hot_dogs,ice_cream,monster,nails,sunscreen: 4
batteries,ice_cream,rice_porridge,sunscreen: 15
batteries,hot_dogs,ice_cream,monster,nails: 1
knives,monster: 19
batteries,ice_cream,monster,nails,rice_porridge,sunscreen: 1
batteries,hot_dogs,ice_cream,monster,sunscreen: 4
hammer,hot_dogs,monster,rice_porridge: 5
batteries,hot_dogs,knives,laderhosen,monster,rice_porridge: 2
hammer,hot_dogs,nails,sunscreen: 1
batteries,hammer,nails,rice_porridge: 3
ice_cream,knives,monster,sunscreen: 7
hot_dogs,ice_cream,laderhosen,monster,rice_porridge,sunscreen: 2
knives,sunscreen: 81
batteries,nails,rice_porridge: 2
hammer: 146
batteries,hammer,hot_dogs,monster,nails: 3
ice_cream,laderhosen,monster,sunscreen: 2
batteries,hammer,ice_cream,monster,nails,sunscreen: 7
batteries,hammer,hot_dogs,monster,nails,rice_porridge: 3
batteries,hammer,hot_dogs,nails,rice_porridge: 4
batteries,hammer,hot_dogs,ice_cream,monster,sunscreen: 1
batteries,hammer,monster: 3
batteries,hot_dogs,laderhosen,monster,sunscreen: 1
batteries,hammer,knives,monster,nails: 3
batteries,hammer,hot_dogs,ice_cream,nails,sunscreen: 3
batteries,hammer,hot_dogs,nails,sunscreen: 1
batteries,hot_dogs,monster,nails,rice_porridge: 3
hammer,knives,nails,sunscreen: 3
batteries,hammer,ice_cream,nails,sunscreen: 7
hot_dogs,ice_cream,monster,rice_porridge: 7
batteries,hot_dogs,laderhosen,monster,rice_porridge: 2
batteries,hot_dogs,laderhosen,nails,rice_porridge: 1
batteries,laderhosen,monster,nails: 1
hot_dogs,monster,nails,rice_porridge,sunscreen: 3
hammer,hot_dogs,laderhosen,nails,rice_porridge,sunscreen: 1
batteries,laderhosen,monster,nails,rice_porridge: 1
hot_dogs,ice_cream,laderhosen,monster,nails,rice_porridge,sunscreen: 1
hammer,ice_cream,monster,sunscreen: 2
batteries,hammer,hot_dogs: 1
batteries,hammer,hot_dogs,laderhosen,rice_porridge: 1
ice_cream,laderhosen,nails,sunscreen: 1
batteries,hammer,ice_cream: 3
batteries,hot_dogs,ice_cream,knives,monster,nails,rice_porridge,sunscreen: 2
batteries,hot_dogs,ice_cream,knives,rice_porridge,sunscreen: 2
hot_dogs,laderhosen,monster,rice_porridge: 3
laderhosen,mattress,monster: 1
knives,nails: 8
hot_dogs,mattress,rice_porridge: 1
hot_dogs,ice_cream,monster: 3
batteries,hammer,hot_dogs,ice_cream,nails,rice_porridge,sunscreen: 2
batteries,hot_dogs,ice_cream,nails,sunscreen: 1
hammer,monster: 5
batteries,hammer,ice_cream,nails,rice_porridge,sunscreen: 6
hammer,hot_dogs,knives,laderhosen,monster,nails,rice_porridge: 2
knives,laderhosen: 68
batteries,hot_dogs,knives: 4
hot_dogs,ice_cream,knives,monster,rice_porridge,sunscreen: 11
laderhosen,monster,rice_porridge,sunscreen: 1
hot_dogs,ice_cream,knives,sunscreen: 1
batteries,hammer,hot_dogs,mattress,monster,rice_porridge: 1
batteries,ice_cream,mattress,monster,sunscreen: 1
batteries,ice_cream,knives,monster,nails,rice_porridge: 1
hot_dogs,knives,monster: 2
hot_dogs,laderhosen,monster,rice_porridge,sunscreen: 1
hammer,hot_dogs,knives,nails: 2
ice_cream,knives,rice_porridge: 8
knives,laderhosen,mattress,nails,sunscreen: 1
ice_cream,knives,laderhosen,rice_porridge: 2
hot_dogs,knives,monster,rice_porridge: 22
hammer,hot_dogs,ice_cream,nails,sunscreen: 2
mattress,rice_porridge: 4
batteries,hammer,monster,rice_porridge: 1
batteries,ice_cream,knives,nails,sunscreen: 6
hot_dogs,ice_cream,knives,laderhosen,monster,rice_porridge,sunscreen: 2
hammer,knives,monster: 1
batteries,ice_cream,knives,monster,sunscreen: 9
batteries,hammer: 23
hammer,hot_dogs,knives,monster,nails,rice_porridge: 2
batteries,hot_dogs,monster,nails,sunscreen: 1
ice_cream,knives,sunscreen: 20
knives,monster,nails: 7
batteries,hammer,laderhosen,monster: 1
batteries,hot_dogs,ice_cream,knives,monster: 3
ice_cream,knives,laderhosen,nails: 1
hammer,hot_dogs,mattress,monster: 1
batteries,hot_dogs,knives,nails: 2
batteries,hot_dogs,laderhosen,mattress,rice_porridge: 1
batteries,hot_dogs,knives,monster,nails,rice_porridge: 2
batteries,knives: 67
batteries,hammer,hot_dogs,ice_cream,knives,monster,rice_porridge,sunscreen: 1
batteries,hammer,ice_cream,knives,monster,nails,sunscreen: 1
hot_dogs,ice_cream,monster,nails,rice_porridge: 4
batteries,hammer,laderhosen,nails: 1
batteries,knives,laderhosen,monster: 5
hammer,hot_dogs,ice_cream,monster,nails,rice_porridge: 1
batteries,hammer,knives,rice_porridge: 14
batteries,hot_dogs,knives,monster,rice_porridge: 4
hammer,ice_cream,knives,nails: 4
hot_dogs,mattress,sunscreen: 1
batteries,laderhosen,monster: 3
ice_cream,knives,rice_porridge,sunscreen: 7
batteries,hot_dogs,mattress,monster,rice_porridge: 1
hot_dogs,knives,mattress,rice_porridge: 1
hot_dogs,knives,nails: 3
hot_dogs,ice_cream,knives,nails,rice_porridge,sunscreen: 1
knives,monster,sunscreen: 3
hot_dogs,knives,mattress,monster,nails: 1
knives,mattress,monster,rice_porridge,sunscreen: 1
hammer,hot_dogs,ice_cream,monster,nails: 3
batteries,hot_dogs,knives,rice_porridge: 10
batteries,ice_cream,monster,nails: 2
ice_cream,knives,monster,nails,sunscreen: 4
hammer,hot_dogs,ice_cream,knives,laderhosen,monster,rice_porridge: 1
batteries,hammer,hot_dogs,ice_cream,rice_porridge: 1
batteries,hammer,hot_dogs,ice_cream,laderhosen,monster,sunscreen: 1
batteries,hammer,hot_dogs,ice_cream,knives,rice_porridge,sunscreen: 1
hot_dogs,knives,mattress,monster,rice_porridge: 2
batteries,ice_cream,laderhosen,mattress,sunscreen: 1
batteries,hot_dogs,ice_cream,knives,monster,rice_porridge: 4
hot_dogs,ice_cream,knives,rice_porridge: 3
hammer,ice_cream,knives,monster,rice_porridge,sunscreen: 2
batteries,hammer,knives,nails: 4
batteries,hammer,ice_cream,laderhosen,monster: 1
batteries,rice_porridge: 70
hammer,hot_dogs,ice_cream,knives,monster,nails,rice_porridge,sunscreen: 4
hammer,hot_dogs,ice_cream,laderhosen,monster,rice_porridge: 1
hammer,hot_dogs,ice_cream,knives,nails,rice_porridge,sunscreen: 2
hammer,hot_dogs,ice_cream,laderhosen,sunscreen: 1
batteries,knives,monster,nails: 1
hot_dogs,ice_cream,knives,rice_porridge,sunscreen: 4
batteries,gjokur_ja,hot_dogs,laderhosen,monster: 2
batteries,hammer,knives,monster: 2
knives,mattress: 19
batteries,hammer,ice_cream,monster,nails,rice_porridge: 1
hammer,hot_dogs,ice_cream,rice_porridge,sunscreen: 2
gjokur_ja,hammer,ice_cream,laderhosen,nails,sunscreen: 1
batteries,hammer,hot_dogs,ice_cream,monster,rice_porridge,sunscreen: 3
hammer,knives,monster,nails: 7
batteries,hot_dogs,knives,monster,rice_porridge,sunscreen: 1
knives,monster,rice_porridge: 4
hot_dogs,laderhosen: 1
hot_dogs,knives,rice_porridge: 3
hammer,ice_cream,mattress,monster: 1
knives,laderhosen,monster,nails: 1
mattress,monster: 3
hammer,ice_cream,mattress,monster,nails,sunscreen: 1
batteries,monster,nails: 8
gjokur_ja,hammer,laderhosen,nails: 1
batteries,hammer,hot_dogs,knives,monster,rice_porridge: 1
hammer,ice_cream,monster,rice_porridge,sunscreen: 1
hammer,laderhosen: 24
batteries,ice_cream,knives: 11
hot_dogs,knives,monster,rice_porridge,sunscreen: 1
batteries,hot_dogs,ice_cream,laderhosen,sunscreen: 2
batteries,hot_dogs,monster,sunscreen: 1
batteries,hot_dogs,ice_cream,knives,rice_porridge: 2
batteries,hot_dogs,knives,monster: 4
batteries,hammer,ice_cream,knives,monster,nails: 2
hammer,knives,monster,nails,sunscreen: 2
batteries,knives,nails: 5
ice_cream,monster,rice_porridge: 10
hammer,hot_dogs,ice_cream,knives,laderhosen,monster: 1
batteries,hammer,ice_cream,rice_porridge,sunscreen: 5
batteries,hammer,hot_dogs,knives,monster,nails: 2
batteries,hot_dogs,ice_cream,knives,mattress,monster,rice_porridge,sunscreen: 1
hammer,hot_dogs,knives,laderhosen,monster,nails: 1
batteries,hammer,ice_cream,knives,sunscreen: 3
mattress,monster,nails: 1
hammer,hot_dogs,laderhosen,mattress,monster,nails,rice_porridge: 1
hammer,ice_cream,knives,laderhosen,nails: 2
batteries,hot_dogs,ice_cream,knives,sunscreen: 5
batteries,ice_cream,knives,monster: 3
mattress: 215
batteries,ice_cream,knives,nails: 3
gjokur_ja,knives,laderhosen,monster,sunscreen: 1
batteries,ice_cream,monster,nails,rice_porridge: 1
batteries,hot_dogs,knives,mattress,monster,nails,rice_porridge: 1
batteries,hammer,hot_dogs,rice_porridge: 1
mattress,nails: 1
hammer,hot_dogs,ice_cream,mattress,monster,rice_porridge: 1
batteries,hammer,knives,mattress: 1
hammer,ice_cream,knives,monster,nails,rice_porridge,sunscreen: 2
knives,laderhosen,nails: 1
hammer,hot_dogs,mattress,nails,rice_porridge: 1
batteries,hammer,ice_cream,knives: 3
batteries,hammer,hot_dogs,knives,rice_porridge,sunscreen: 1
batteries,gjokur_ja,hot_dogs,knives,laderhosen,monster,nails,rice_porridge,sunscreen: 1
batteries,hammer,monster,nails: 5
hot_dogs,ice_cream,knives,monster,rice_porridge: 4
hot_dogs,laderhosen,mattress,monster,rice_porridge: 1
laderhosen,monster,sunscreen: 1
batteries,hot_dogs,laderhosen,monster: 2
batteries,hammer,ice_cream,monster: 2
hot_dogs,ice_cream,knives,monster,nails: 2
hammer,hot_dogs,monster: 1
hot_dogs,ice_cream,knives,monster,nails,rice_porridge,sunscreen: 2
batteries,hot_dogs,laderhosen,monster,nails,rice_porridge: 1
batteries,hammer,knives,mattress,monster,nails: 1
ice_cream,knives: 10
hammer,hot_dogs,ice_cream,monster,sunscreen: 2
hammer,hot_dogs,mattress,monster,nails: 1
batteries,hammer,hot_dogs,knives,sunscreen: 1
hot_dogs,ice_cream,knives,monster: 2
batteries,hot_dogs,laderhosen,rice_porridge: 1
hammer,ice_cream,knives,monster,sunscreen: 1
ice_cream,knives,monster,rice_porridge,sunscreen: 3
hot_dogs,ice_cream,knives,monster,sunscreen: 4
hammer,ice_cream,knives,monster,nails,sunscreen: 4
batteries,ice_cream,knives,laderhosen,nails: 1
hot_dogs,mattress,monster,nails: 1
hammer,hot_dogs,ice_cream,monster,rice_porridge: 2
batteries,hammer,hot_dogs,knives,laderhosen,nails,rice_porridge: 2
batteries,hammer,ice_cream,sunscreen: 6
hot_dogs,knives,laderhosen: 1
batteries,gjokur_ja,hammer,ice_cream,laderhosen,mattress,monster,sunscreen: 1
ice_cream,knives,mattress,monster,sunscreen: 2
ice_cream,knives,nails,sunscreen: 7
batteries,ice_cream,knives,sunscreen: 18
hammer,hot_dogs,laderhosen,mattress,nails,rice_porridge: 1
batteries,hammer,ice_cream,mattress,nails: 1
ice_cream,rice_porridge: 12
knives,rice_porridge,sunscreen: 27
hot_dogs,ice_cream,knives,nails,rice_porridge: 3
batteries,hot_dogs,knives,monster,nails: 3
hammer,knives,laderhosen,monster,nails,sunscreen: 1
hot_dogs,rice_porridge,sunscreen: 1
hot_dogs,knives,nails,rice_porridge: 3
batteries,knives,laderhosen: 13
knives: 556
hammer,ice_cream,knives,sunscreen: 4
batteries,ice_cream,mattress,sunscreen: 1
hammer,hot_dogs,knives,monster,rice_porridge: 1
batteries,hammer,ice_cream,laderhosen,mattress,monster,rice_porridge: 1
ice_cream,knives,monster,rice_porridge: 1
hot_dogs,ice_cream,knives,mattress,rice_porridge,sunscreen: 2
batteries,hot_dogs,knives,laderhosen,monster,nails,rice_porridge: 1
batteries,hammer,hot_dogs,knives,nails: 2
ice_cream,laderhosen,mattress,rice_porridge,sunscreen: 1
batteries,hammer,hot_dogs,knives,monster,nails,rice_porridge: 1
hammer,hot_dogs,ice_cream,knives,monster,nails,rice_porridge: 1
hammer,hot_dogs,knives,monster: 1
ice_cream,knives,laderhosen,monster,sunscreen: 1
hammer,ice_cream,knives,mattress,monster,nails,sunscreen: 1
batteries,hammer,hot_dogs,monster,rice_porridge: 1
batteries,knives,nails,rice_porridge: 5
batteries,knives,mattress,monster,nails: 2
batteries,hammer,hot_dogs,nails,rice_porridge,sunscreen: 1
batteries,hammer,knives,monster,sunscreen: 1
batteries,hammer,knives,laderhosen,monster,nails: 1
ice_cream,knives,nails: 2
batteries,hammer,hot_dogs,ice_cream,knives,monster,nails,rice_porridge: 1
hot_dogs,laderhosen,monster,sunscreen: 1
hammer,hot_dogs,ice_cream,knives,nails,rice_porridge: 1
knives,rice_porridge: 57
batteries,hammer,hot_dogs,ice_cream,knives,rice_porridge: 2
batteries,hammer,ice_cream,monster,nails: 3
batteries,gjokur_ja,hot_dogs,ice_cream,laderhosen,monster: 1
batteries,hammer,knives,monster,nails,sunscreen: 2
laderhosen,rice_porridge: 7
batteries,hammer,ice_cream,knives,monster,sunscreen: 1
batteries,hot_dogs,ice_cream,knives,nails,rice_porridge,sunscreen: 2
batteries,hammer,hot_dogs,ice_cream,monster,nails,sunscreen: 1
batteries,hammer,hot_dogs,ice_cream,knives,nails,sunscreen: 2
laderhosen,monster,rice_porridge: 2
batteries,hammer,ice_cream,knives,nails,sunscreen: 4
hot_dogs,ice_cream,knives,laderhosen,monster,nails,rice_porridge: 1
hammer,hot_dogs,ice_cream,knives,nails,sunscreen: 1
batteries,hammer,hot_dogs,knives,rice_porridge: 2
ice_cream,knives,laderhosen,sunscreen: 3
batteries,hot_dogs,mattress,rice_porridge: 1
hammer,hot_dogs,rice_porridge: 1
batteries,laderhosen,sunscreen: 3
batteries,ice_cream,knives,monster,nails,sunscreen: 1
hot_dogs,knives,nails,sunscreen: 1
hot_dogs,ice_cream,laderhosen,monster,rice_porridge: 1
batteries,hammer,mattress,nails: 2
batteries,hammer,hot_dogs,mattress,nails,rice_porridge: 1
batteries,hammer,ice_cream,mattress,monster,nails,sunscreen: 1
batteries,ice_cream,monster,rice_porridge,sunscreen: 2
batteries,hammer,hot_dogs,rice_porridge,sunscreen: 1
batteries,hot_dogs,knives,laderhosen,mattress,monster,rice_porridge: 1
batteries,ice_cream,knives,laderhosen,monster,rice_porridge: 1
hammer,knives,sunscreen: 23
hot_dogs,knives: 2
batteries,hammer,ice_cream,knives,monster,rice_porridge: 1
hammer,knives,monster,rice_porridge: 3
batteries,hammer,hot_dogs,ice_cream,knives,laderhosen,monster,nails,rice_porridge,sunscreen: 1
batteries,knives,monster,nails,sunscreen: 2
batteries,hammer,hot_dogs,laderhosen,monster,nails,rice_porridge: 1
hammer,monster,nails,sunscreen: 1
hammer,hot_dogs,mattress,rice_porridge: 1
hot_dogs,knives,monster,nails,rice_porridge: 3
hammer,hot_dogs,ice_cream,monster: 1
hot_dogs,ice_cream,knives,monster,nails,sunscreen: 2
hammer,hot_dogs,ice_cream,sunscreen: 1
batteries,hot_dogs,ice_cream,knives,nails,rice_porridge: 1
hammer,hot_dogs,ice_cream,laderhosen,monster,nails,rice_porridge,sunscreen: 1
gjokur_ja,knives,laderhosen: 4
hammer,hot_dogs,knives,monster,nails: 1
batteries,ice_cream,nails: 4
batteries,ice_cream,laderhosen,rice_porridge,sunscreen: 2
batteries,ice_cream,nails,rice_porridge,sunscreen: 1
batteries,hot_dogs,ice_cream,laderhosen,mattress,monster: 1
hammer,hot_dogs,knives,monster,nails,rice_porridge,sunscreen: 1
batteries,hammer,ice_cream,knives,nails,rice_porridge: 2
hot_dogs,ice_cream,knives: 1
batteries,knives,laderhosen,monster,rice_porridge: 1
hammer,laderhosen,monster,nails: 2
batteries,hammer,hot_dogs,knives,laderhosen,monster,nails,rice_porridge: 1
batteries,hammer,ice_cream,knives,mattress,monster,sunscreen: 1
hammer,ice_cream,laderhosen,mattress,nails,sunscreen: 2
batteries,hot_dogs,ice_cream,knives,laderhosen,monster,rice_porridge,sunscreen: 1
batteries,ice_cream,knives,mattress,monster,sunscreen: 1
batteries,hammer,knives,mattress,monster,nails,rice_porridge: 1
batteries,knives,monster,nails,rice_porridge: 2
ice_cream,laderhosen,mattress,sunscreen: 1
knives,nails,rice_porridge: 1
hammer,hot_dogs,ice_cream,knives,monster,nails: 1
hammer,rice_porridge,sunscreen: 4
batteries,hammer,ice_cream,monster,sunscreen: 2
batteries,hammer,hot_dogs,ice_cream,knives,nails,rice_porridge: 1
ice_cream,mattress,monster,sunscreen: 1
laderhosen,nails,rice_porridge: 2
hot_dogs,ice_cream,mattress,monster,rice_porridge: 1
batteries,hammer,hot_dogs,ice_cream,knives,monster,nails,rice_porridge,sunscreen: 1
ice_cream,laderhosen,rice_porridge,sunscreen: 4
batteries,hot_dogs,laderhosen,rice_porridge,sunscreen: 1
batteries,hammer,monster,nails,rice_porridge: 1
hot_dogs,ice_cream,knives,nails,sunscreen: 1
batteries,knives,monster,rice_porridge: 1
hot_dogs,ice_cream,laderhosen: 1
batteries,hammer,hot_dogs,ice_cream,monster,nails,rice_porridge,sunscreen: 1
batteries,gjokur_ja,hammer,knives,laderhosen,monster,rice_porridge: 1
ice_cream,knives,mattress,monster,nails: 1
hammer,hot_dogs,knives,nails,rice_porridge: 1
batteries,hammer,mattress,monster,rice_porridge: 1
hot_dogs,knives,monster,nails: 1
hammer,hot_dogs: 1
batteries,knives,rice_porridge: 37
batteries,hammer,laderhosen,nails,sunscreen: 1
batteries,hot_dogs,mattress,monster,nails: 1
batteries,hammer,knives,laderhosen,nails: 3
hammer,hot_dogs,rice_porridge,sunscreen: 1
ice_cream,mattress,monster,rice_porridge: 1
batteries,ice_cream,knives,laderhosen,mattress,monster: 2
batteries,knives,monster,sunscreen: 1
batteries,hot_dogs,ice_cream,monster,nails,rice_porridge,sunscreen: 1
hot_dogs,ice_cream,mattress,rice_porridge,sunscreen: 1
batteries,ice_cream,knives,monster,rice_porridge,sunscreen: 3
knives,laderhosen,mattress: 8
batteries,ice_cream,knives,rice_porridge,sunscreen: 9
batteries,hammer,monster,nails,rice_porridge,sunscreen: 1
hammer,laderhosen,monster,nails,rice_porridge,sunscreen: 1
hammer,ice_cream,knives,rice_porridge,sunscreen: 3
monster,nails,rice_porridge,sunscreen: 1
batteries,hammer,ice_cream,knives,monster,nails,rice_porridge,sunscreen: 2
batteries,ice_cream,laderhosen: 2
batteries,hammer,ice_cream,knives,monster,nails,rice_porridge: 2
hammer,knives,rice_porridge: 14
ice_cream,knives,monster: 4
batteries,ice_cream,laderhosen,nails: 1
batteries,gjokur_ja,ice_cream,laderhosen,rice_porridge: 1
hammer,ice_cream,knives,laderhosen,monster,nails,rice_porridge,sunscreen: 1
hammer,ice_cream,knives,monster: 1
knives,laderhosen,monster,nails,rice_porridge: 1
ice_cream,mattress,sunscreen: 5
mattress,monster,nails,rice_porridge: 1
hammer,knives,laderhosen,mattress,monster: 1
mattress,monster,rice_porridge: 1
batteries,ice_cream,knives,nails,rice_porridge,sunscreen: 2
batteries,laderhosen,mattress,monster: 1
hammer,knives,nails: 10
batteries,hammer,monster,nails,sunscreen: 1
hammer,ice_cream,knives,laderhosen,monster,nails,sunscreen: 1
hammer,knives,laderhosen,nails: 1
batteries,ice_cream,monster,rice_porridge: 1
mattress,monster,nails,sunscreen: 1
hammer,knives,laderhosen,monster: 1
batteries,hammer,ice_cream,laderhosen,nails,rice_porridge,sunscreen: 1
ice_cream,knives,mattress,monster,nails,rice_porridge: 1
batteries,laderhosen,nails,rice_porridge,sunscreen: 1
hammer,knives,monster,nails,rice_porridge: 3
batteries,ice_cream,knives,monster,nails,rice_porridge,sunscreen: 1
ice_cream,knives,laderhosen,monster,rice_porridge,sunscreen: 1
batteries,knives,monster,rice_porridge,sunscreen: 1
hammer,knives,monster,nails,rice_porridge,sunscreen: 1
hammer,ice_cream,monster,nails,rice_porridge: 2
knives,monster,nails,rice_porridge: 1
batteries,ice_cream,knives,mattress,monster,nails,rice_porridge: 1
batteries,ice_cream,knives,mattress,rice_porridge,sunscreen: 1
hammer,knives,laderhosen,nails,rice_porridge: 1
ice_cream,mattress,nails,sunscreen: 1
batteries,hammer,ice_cream,knives,laderhosen,sunscreen: 1
hammer,ice_cream,knives,nails,sunscreen: 3
knives,mattress,nails: 1
hammer,ice_cream,knives,laderhosen,rice_porridge: 1
batteries,hammer,ice_cream,knives,nails: 3
laderhosen,mattress: 46
hammer,laderhosen,rice_porridge: 2
hammer,laderhosen,mattress,nails,rice_porridge: 1
batteries,ice_cream,laderhosen,rice_porridge: 1
batteries,hammer,knives: 17
hammer,ice_cream,laderhosen,mattress,nails,rice_porridge: 1
batteries,ice_cream,laderhosen,sunscreen: 2
laderhosen,mattress,nails,rice_porridge: 1
hammer,ice_cream,knives,nails,rice_porridge,sunscreen: 3
batteries,hammer,ice_cream,laderhosen,nails: 1
batteries,ice_cream,knives,rice_porridge: 4
batteries,hammer,ice_cream,knives,rice_porridge: 1
batteries,hammer,knives,nails,rice_porridge: 3
hammer,ice_cream,mattress,rice_porridge,sunscreen: 1
batteries,hammer,nails,rice_porridge,sunscreen: 1
ice_cream,knives,laderhosen: 1
batteries,knives,sunscreen: 32
ice_cream,knives,laderhosen,nails,sunscreen: 1
hammer,rice_porridge: 14
batteries,hammer,ice_cream,laderhosen,sunscreen: 2
batteries,mattress,nails,rice_porridge,sunscreen: 1
batteries,hammer,ice_cream,knives,rice_porridge,sunscreen: 2
hammer,ice_cream,laderhosen,nails: 1
knives,laderhosen,rice_porridge,sunscreen: 1
batteries,knives,mattress,nails: 2
ice_cream,knives,laderhosen,nails,rice_porridge: 1
hammer,ice_cream,nails,rice_porridge,sunscreen: 1
hammer,knives,nails,rice_porridge: 1
ice_cream,mattress: 3
batteries,hammer,ice_cream,laderhosen,nails,sunscreen: 1
hammer,knives,nails,rice_porridge,sunscreen: 1
batteries,laderhosen,rice_porridge: 8
knives,mattress,rice_porridge: 4
hammer,ice_cream,rice_porridge: 3
hammer,ice_cream,sunscreen: 1
batteries,hammer,ice_cream,knives,nails,rice_porridge,sunscreen: 1
ice_cream,knives,nails,rice_porridge,sunscreen: 1
hammer,ice_cream,knives: 4
batteries,laderhosen,mattress: 2
hammer,mattress,nails,rice_porridge: 1
hammer,ice_cream,nails,rice_porridge: 3
hammer,knives: 91
batteries,mattress,rice_porridge: 3
hammer,nails,sunscreen: 1
hammer,ice_cream,knives,laderhosen,nails,rice_porridge: 1
batteries,hammer,ice_cream,rice_porridge: 1
hammer,ice_cream,knives,laderhosen,nails,rice_porridge,sunscreen: 1
batteries,gjokur_ja,laderhosen,sunscreen: 1
hammer,ice_cream,rice_porridge,sunscreen: 1
laderhosen,nails: 1
knives,laderhosen,rice_porridge: 16
knives,laderhosen,nails,rice_porridge: 1
ice_cream,knives,laderhosen,rice_porridge,sunscreen: 1
batteries,laderhosen,rice_porridge,sunscreen: 2
hammer,ice_cream: 2
batteries,hammer,ice_cream,knives,mattress,rice_porridge,sunscreen: 1
hammer,nails,rice_porridge,sunscreen: 1
batteries,knives,mattress: 5
batteries,hammer,ice_cream,knives,mattress,nails,rice_porridge: 1
batteries,hammer,rice_porridge: 14
batteries,ice_cream,knives,nails,rice_porridge: 1
batteries,knives,mattress,sunscreen: 3
batteries,hammer,ice_cream,mattress,rice_porridge,sunscreen: 1
hammer,mattress,rice_porridge: 1
batteries,rice_porridge,sunscreen: 10
laderhosen,rice_porridge,sunscreen: 2
hammer,ice_cream,knives,rice_porridge: 3
knives,mattress,rice_porridge,sunscreen: 3
batteries,hammer,ice_cream,knives,laderhosen: 1
batteries,ice_cream,mattress,rice_porridge: 1
batteries,mattress: 6
hammer,ice_cream,knives,mattress,sunscreen: 1
hammer,ice_cream,knives,laderhosen,rice_porridge,sunscreen: 2
knives,mattress,sunscreen: 7
batteries,ice_cream,knives,laderhosen: 1
batteries,hammer,ice_cream,laderhosen,rice_porridge: 1
hammer,ice_cream,laderhosen,sunscreen: 1
ice_cream,knives,mattress,sunscreen: 1
batteries,hammer,laderhosen: 4
batteries,gjokur_ja,laderhosen,mattress: 1
batteries,hammer,ice_cream,knives,mattress,rice_porridge: 1
hammer,ice_cream,laderhosen,rice_porridge,sunscreen: 1
batteries,hammer,mattress,sunscreen: 1
batteries,hammer,knives,laderhosen: 1
hammer,sunscreen: 32
gjokur_ja,laderhosen: 24
batteries,knives,rice_porridge,sunscreen: 9
batteries,hammer,knives,sunscreen: 5
batteries,mattress,rice_porridge,sunscreen: 2
batteries,hammer,sunscreen: 11
batteries,knives,mattress,rice_porridge,sunscreen: 2
mattress,rice_porridge,sunscreen: 3
batteries,hammer,knives,laderhosen,sunscreen: 1
batteries,hammer,knives,laderhosen,rice_porridge,sunscreen: 1
mattress,sunscreen: 6
knives,laderhosen,sunscreen: 17
batteries,hammer,laderhosen,rice_porridge: 2
batteries,gjokur_ja,hammer,knives,laderhosen,mattress,rice_porridge,sunscreen: 1
hammer,mattress: 13
batteries,hammer,knives,rice_porridge,sunscreen: 2
hammer,knives,laderhosen: 11
batteries,knives,laderhosen,mattress: 2
hammer,knives,rice_porridge,sunscreen: 1
batteries,knives,laderhosen,rice_porridge,sunscreen: 1
batteries,hammer,laderhosen,sunscreen: 1
hammer,knives,mattress: 5
batteries,knives,laderhosen,rice_porridge: 2
hammer,laderhosen,rice_porridge,sunscreen: 2
batteries,hammer,laderhosen,mattress: 1
batteries,knives,laderhosen,sunscreen: 3
batteries,gjokur_ja,laderhosen,rice_porridge,sunscreen: 1
hammer,knives,laderhosen,sunscreen: 6
batteries,knives,mattress,rice_porridge: 1
batteries,laderhosen,mattress,rice_porridge: 1
batteries,gjokur_ja,laderhosen: 1
batteries,mattress,sunscreen: 1
hammer,knives,laderhosen,rice_porridge,sunscreen: 1
hammer,knives,mattress,rice_porridge: 1
hammer,knives,laderhosen,mattress,rice_porridge: 1
knives,laderhosen,mattress,rice_porridge: 1
hammer,laderhosen,sunscreen: 3
laderhosen,mattress,sunscreen: 3
hammer,knives,mattress,sunscreen: 1
hammer,knives,laderhosen,mattress: 2
gjokur_ja,laderhosen,sunscreen: 1
hammer,laderhosen,mattress,sunscreen: 1
gjokur_ja,hammer,knives,laderhosen: 1
gjokur_ja,laderhosen,mattress: 1
dinosaur,laderhosen: 1
"""

# Step 1: Parse "combo: count" lines
pattern = re.compile(r"^\s*([a-zA-Z0-9_,]+)\s*:\s*(\d+)\s*$")
pairs = []
for line in raw.strip().splitlines():
    m = pattern.match(line)
    if m:
        combo = tuple(part.strip() for part in m.group(1).split(","))
        count = int(m.group(2))
        pairs.append((combo, count))

# Step 2: Collect all unique merch types
all_items = sorted(set(itertools.chain.from_iterable(combo for combo, _ in pairs)))

# Step 3: Build co-occurrence matrix (including diagonal as total item frequency)
idx = {item: i for i, item in enumerate(all_items)}
mat = np.zeros((len(all_items), len(all_items)), dtype=float)

for combo, count in pairs:
    items = list(combo)
    # Diagonals: add count for each item present in this combo
    for item in items:
        i = idx[item]
        mat[i, i] += count
    # Off-diagonals: add count to each pair that co-occurs
    for a, b in itertools.combinations(items, 2):
        i, j = idx[a], idx[b]
        mat[i, j] += count
        mat[j, i] += count

# Step 4: Order items by descending total frequency (diagonal)
order = np.argsort(-np.diag(mat))
ordered_items = [all_items[i] for i in order]
mat_ord = mat[order][:, order]

# Step 5: Create a DataFrame for the ordered matrix
df = pd.DataFrame(mat_ord, index=ordered_items, columns=ordered_items).astype(int)

# Save the matrix as CSV
out_dir = Path("/mnt/data")
out_dir.mkdir(parents=True, exist_ok=True)
csv_path = out_dir / "merch_cooccurrence_matrix.csv"
df.to_csv(csv_path)

# Step 6: Plot a heatmap using log1p to handle wide ranges without specifying colors
plt.figure(figsize=(10, 9))
plt.imshow(np.log1p(df.values))
plt.xticks(ticks=np.arange(len(ordered_items)), labels=ordered_items, rotation=90)
plt.yticks(ticks=np.arange(len(ordered_items)), labels=ordered_items)
plt.title("Merch Types Co-occurrence Heatmap (log1p scale)")
plt.colorbar(label="log1p(count)")
plt.tight_layout()

png_path = out_dir / "merch_cooccurrence_heatmap.png"
plt.savefig(png_path, dpi=200)
plt.show()

# Also display the DataFrame interactively
import caas_jupyter_tools
caas_jupyter_tools.display_dataframe_to_user("Co-occurrence Matrix (counts)", df)

print(f"Saved CSV to: {csv_path}")
print(f"Saved PNG to: {png_path}")
